config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  root 'contacts#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :group
  # add validation
  validates :name, :company, :contactphone, :telegram, :whatsapp, :viber, :history, presence: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://placehold.it/100x100&text=No+Image"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # find contact before actions
  before_action :find_contact, only: [:edit, :update, :destroy]

  def index
    if params[:group_id]
      @group = Group.find(params[:group_id])
      @contacts = @group.contacts.paginate(page: params[:page], per_page: 10)
    else
      @contacts = Contact.paginate(page: params[:page], per_page: 10)
    end
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = "Succesfully created new contact"
      redirect_to contacts_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update

    if @contact.update(contact_params)
      flash[:success] = "Successfully updated contact!"
      redirect_to contacts_path
    else
      render 'edit'
    end
  end

  def destroy

    @contact.destroy
    flash[:success] = "Successfully deleted contact"
    redirect_to contacts_path
  end

  private

  def find_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :company, :email, :contactphone, :workphone, :address, :telegram, :whatsapp, :viber, :history, :avatar, :group_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.erb
<%= form_for @contact do |f| %>
<div class="panel-body">

  <% if @contact.errors.any? %>

  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger">
        <h3> Please correct this following errors: </h3>
        <ul>
            <% @contact.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>

      </div>
    </div>
  </div>

  <% end %>

  <div class="form-horizontal">
    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <%= f.label :name, class: "control-label col-md-3" %>
          <!-- <label for="name" class="control-label col-md-3">Name</label> -->
          <div class="col-md-8">
            <%= f.text_field :name, class: "form-control" %>
            <!-- <input type="text" name="name" id="name" class="form-control>" -->
          </div>
        </div>

        <div class="form-group">
          <%= f.label :company, class: "control-label col-md-3" %>
          <!-- <label for="company" class="control-label col-md-3">Company</label> -->
          <div class="col-md-8">
            <%= f.text_field :company, class: "form-control" %>
            <!-- <input type="text" name="company" id="company" class="form-control"> -->
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :email, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :contactphone, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :contactphone, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :workphone, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :workphone, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :address, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_area :address, class: "form-control" %>
          </div>
        </div>


        <div class="form-check">
          <%= f.label :telegram, class: "form-check-label col-md-3" %>
          <div class="col-md-8">
            <%= f.check_box :telegram, class: "form-check-input" %>
          </div>
        </div>
        <div class="form-check">
          <%= f.label :viber, class: "form-check-label col-md-3" %>
          <div class="col-md-8">
            <%= f.check_box :viber, class: "form-check-inlput" %>
          </div>
        </div>
        <div class="form-check">
          <%= f.label :whatsapp, class: "form-check-label col-md-3" %>
          <div class="col-md-8">
            <%=f.check_box :whatsapp, class: "form-check-input" %>
          </div>
        </div>



        <div class="form-group">
          <%= f.label :history, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_area :history, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label for="group" id="group" class="control-label col-md-3"></label>
          <div class="col-md-5">
            <select name="group" id="group" class="control-label col-md-3">
              <option value="">Select group</option>
              <option value="1">Family</option>
              <option value="2">Friend</option>
              <option value="3">Other</option>
            </select>
          </div>
        </div>

        <div class="form-group">
            <label for="group" class="control-label col-md-3">Group</label>
            <div class="col-md-5">
              <select name="group" id="group" class="form-control">
                <option value="">Select group</option>
                <option value="1">Relative</option>
                <option value="2">Schoolmates</option>
                <option value="3">MFUAmates</option>
                <option value="4">Coworkers</option>
                <option value="5">Karma</option>
                <option value="6">Programmers</option>
              </select>
            </div>
            <div class="col-md-3">
              <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
            </div>
          </div>
          <div class="form-group" id="add-new-group" style="display: none;">
            <div class="col-md-offset-3 col-md-8">
              <div class="input-group">
                <input type="text" name="new_group" id="new_group" class="form-control">
                <span class="input-group-btn">
                  <a href="#" class="btn btn-default">
                    <i class="glyphicon glyphicon-ok"></i>
                  </a>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="fileinput fileinput-new" data-provides="fileinput">
            <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
              <img src="http://placehold.it/150x150" alt="Photo">
            </div>
            <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
            <div class="text-center">
              <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span><input type="file" name="..."></span>
              <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-offset-3 col-md-6">
            <button type="submit" class="btn btn-primary">Save</button>

            <%= link_to "Cancel", contacts_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<%= form_for @contact, html: { multipart: true} do |f| %>
<div class="panel-body">

  <% if @contact.errors.any? %>

  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger">
        <h3> Please correct this following errors: </h3>
        <ul>
            <% @contact.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>

      </div>
    </div>
  </div>

  <% end %>

  <div class="form-horizontal">
    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <%= f.label :name, class: "control-label col-md-3" %>
          <!-- <label for="name" class="control-label col-md-3">Name</label> -->
          <div class="col-md-8">
            <%= f.text_field :name, class: "form-control" %>
            <!-- <input type="text" name="name" id="name" class="form-control>" -->
          </div>
        </div>

        <div class="form-group">
          <%= f.label :company, class: "control-label col-md-3" %>
          <!-- <label for="company" class="control-label col-md-3">Company</label> -->
          <div class="col-md-8">
            <%= f.text_field :company, class: "form-control" %>
            <!-- <input type="text" name="company" id="company" class="form-control"> -->
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :email, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :contactphone, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :contactphone, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :workphone, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :workphone, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :address, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_area :address, class: "form-control" %>
          </div>
        </div>


        <div class="form-check">
          <%= f.label :telegram, class: "form-check-label col-md-3" %>
          <div class="col-md-8">
            <%= f.check_box :telegram, class: "form-check-input" %>
          </div>
        </div>
        <div class="form-check">
          <%= f.label :viber, class: "form-check-label col-md-3" %>
          <div class="col-md-8">
            <%= f.check_box :viber, class: "form-check-inlput" %>
          </div>
        </div>
        <div class="form-check">
          <%= f.label :whatsapp, class: "form-check-label col-md-3" %>
          <div class="col-md-8">
            <%=f.check_box :whatsapp, class: "form-check-input" %>
          </div>
        </div>



        <div class="form-group">
          <%= f.label :history, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_area :history, class: "form-control" %>
          </div>
        </div>



        <div class="form-group">
            <label for="group" class="control-label col-md-3">Group</label>
            <div class="col-md-5">
              <%= f.collection_select :group_id, Group.all, :id, :name, { prompt: "Select group" }, class: "form-control" %>
            </div>
            <div class="col-md-3">
              <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
            </div>
          </div>
          <div class="form-group" id="add-new-group" style="display: none;">
            <div class="col-md-offset-3 col-md-8">
              <div class="input-group">
                <input type="text" name="new_group" id="new_group" class="form-control">
                <span class="input-group-btn">
                  <a href="#" class="btn btn-default">
                    <i class="glyphicon glyphicon-ok"></i>
                  </a>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="fileinput fileinput-new" data-provides="fileinput">
            <div class="fileinput-new thumbnail" style="width: 200px; height: 200px;">
              <%= image_tag @contact.avatar.url(:medium) %>
            </div>
            <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
            <div class="text-center">
              <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span>
              <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-md-8">
        <div class="row">
          <div class="col-md-offset-3 col-md-6">
            <button type="submit" class="btn btn-primary">Save</button>

            <%= link_to "Cancel", contacts_path, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Edit Contact</strong>
  </div>
  <%= render 'form' %>
</div>

app/views/contacts/index.html.erb
<div class="panel panel-default">
  <table class="table">

    <% @contacts.each do |contact| %>
    <tr>
      <td class="middle">
        <div class="media">
          <div class="media-left">
            <a href="#">
              <%= image_tag contact.avatar.url(:thumb), class: "media-object" %>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= contact.name %></h4>
            <address><strong><%= contact.company%></strong><br>
              <%= contact.email %>
            </address>
          </div>
        </div>
      </td>
      <td width="100" class="middle">
        <div>
          <%= link_to edit_contact_path(contact), class: "btn btn-circle btn-default btn-xs", title: "Edit"  do %>
            <i class="glyphicon glyphicon-edit"></i>
          <% end %>

          <%= link_to contact_path(contact), :method => :delete, class: "btn btn-circle btn-danger btn-xs", title: "Delete", data: { confirm: "Are you sure?"}  do %>
            <i class="glyphicon glyphicon-remove"></i>
          <% end %>

        </div>
      </td>
    </tr>

    <% end %>

  </table>
</div>

<div class="text-center">
  <%= will_paginate %>
</div>

app/views/contacts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Add Contact</strong>
  </div>
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mycontact</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to "My contact", root_path, class: "navbar-brand text-uppercase" %>

      </div>
      <!-- navbar-header -->
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <div class="nav navbar-right navbar-btn">
          <%= link_to new_contact_path, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-plus"></i>
            Add Contact
          <% end %>

        </div>
      </div>
    </div>
  </nav>



<!-- content -->
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="list-group">
        <!-- set active links -->
        <% active = params[:group_id] == nil ? 'active' : '' %>

        <%= link_to contacts_path, class: "list-group-item #{active}" do %>
          All Contacts <span class="badge"><%= Contact.count %></span>
        <% end %>


        <% Group.all.each do |group| %>
          <% active = params[:group_id] == group.id ? 'active' : '' %>
          <%= link_to contacts_path(group_id: group.id), class: "list-group-item #{active}" do %>
            <%= group.name %> <span class="badge"><%= group.contacts.count %></span>
          <% end %>
        <% end %>
      </div>
    </div><!-- /.col-md-3 -->

    <div class="col-md-9">

      <% flash.each do |type, message| %>
        <%= content_tag :div, class: "alert alert-#{type} alert-dismissible", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= message %>
        <% end %>
      <% end %>


      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>